### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'blockshell' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by marie-bnl** [daxeel/blockshell#22]
I installed blockshell by copying all the commands in the readme and when I run `blockshell` I get 
```
Traceback (most recent call last):
  File "/usr/bin/blockshell", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3241, in <module>
    @_call_aside
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'blockshell' distribution was not found and is required by the application
```

**Comment by marie-bnl** [comment]
I must do this command in the venv
