### ISSUE TITLE
I get an error on running blockshell

### ISSUE THREAD

**Issue by palash25** [daxeel/blockshell#6]
I have followed the installation instructions and installed it sucessfully but on running `blockshell` it gives the following error
```
(venv) palash25@Lenovo-G50:~/Dev/bshell/blockshell$ blockshell
Traceback (most recent call last):
  File "/home/palash25/Dev/bshell/venv/bin/blockshell", line 11, in <module>
    load_entry_point('blockshell', 'console_scripts', 'blockshell')()
  File "/home/palash25/Dev/bshell/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/palash25/Dev/bshell/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/home/palash25/Dev/bshell/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/home/palash25/Dev/bshell/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/palash25/Dev/bshell/blockshell/bscli.py", line 60
    """
      ^
SyntaxError: invalid syntax

```

**Comment by daxeel** [comment]
This seems a python version error. Which python version are you using?

**Comment by palash25** [comment]
3.6

**Comment by daxeel** [comment]
As of now, Blockshell supports python2.7.x. Try to create virtual environment in python 2.
